spring:
  application:
    name: Mall
  profiles:
    active: dev
  jpa:
    show-sql: true

    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
  thymeleaf:
    cache: false